WITH T1 AS (
    SELECT CAR_ID, COUNT(CAR_ID) AS COUNT_HISTORY FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
    START_DATE BETWEEN '2022-11-01' AND '2022-11-30' 
    OR END_DATE BETWEEN '2022-11-01' AND '2022-11-30' 
    OR (START_DATE < '2022-11-01' AND END_DATE > '2022-11-30')
GROUP BY CAR_ID ORDER BY CAR_ID ASC
), T2 AS (
    SELECT car.CAR_ID, CAR_TYPE, DAILY_FEE * 30 AS TOTAL_FEE FROM CAR_RENTAL_COMPANY_CAR AS car 
    LEFT JOIN t1 ON car.CAR_ID = t1.CAR_ID 
    WHERE (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV') AND IFNULL(COUNT_HISTORY, 0) = 0
)

SELECT t2.CAR_ID, t2.CAR_TYPE, 
t2.TOTAL_FEE * (100 - discount.DISCOUNT_RATE ) DIV 100 AS FEE
FROM t2 
INNER JOIN (
    SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상') AS discount
ON t2.CAR_TYPE = discount.CAR_TYPE
WHERE t2.TOTAL_FEE * (100 - discount.DISCOUNT_RATE ) DIV 100 BETWEEN 500000 AND 1990000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;