SELECT ap.APNT_NO, pat.PT_NAME, ap.PT_NO, ap.MCDP_CD, doctor.DR_NAME, ap.APNT_YMD 
FROM APPOINTMENT AS ap 
LEFT JOIN PATIENT AS pat ON ap.PT_NO = pat.PT_NO 
LEFT JOIN DOCTOR AS doctor ON ap.MDDR_ID = doctor.DR_ID 
WHERE ap.APNT_YMD BETWEEN '2022-04-13 00:00:00' AND '2022-04-13 23:59:59'
AND ap.APNT_CNCL_YN = 'N'
AND ap.MCDP_CD = 'CS'
ORDER BY ap.APNT_YMD ASC;
# SELECT * FROM APPOINTMENT;